---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    region_name: regionOne
  register: osp_srv_inventory
  tags:
    - osp.delete

- name: Delete instances
  os_server:
   cloud: openstack
   region_name: regionOne
   name: "{{ item.name }}"
   state: absent
  loop: "{{ osp_srv_inventory.openstack_servers }}"
  tags:
    - osp.delete
   
