- hosts: frontends
  gather_facts: false
  tasks:
  - name: debug stuff
    debug:
      msg: "{{ groups['frontends'] }}"
  - name: Curl website
    uri:
      url: "http://{{ item }}"
      return_content: yes
      status_code: 200
    loop: "{{ groups['frontends'] }}"
    register: webpage
        
  - debug: var=webpage.content

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"

