---
- name: debug stuff
  debug:
    msg: "{{ hostvars }}"
- name: Install load balancer packages
  package:
    name: "{{ groups['apps'] }}"
    state: present
  tags:
    - haproxy

# Included due to an issue with the existing haproxy template, app1/app2, work on prod not QA, vice-versa.
- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
  tags:
    - haproxy
  ignore_errors: yes

- name: Print Config
  command: cat /etc/haproxy/haproxy.cfg
  ignore_errors: yes
  register: testvar

- debug:
    msg: "{{ testvar }}"
  ignore_errors: yes

- name: Ensure HAProxy Service is Enabled
  service:
    name: "{{ payload }}"
    state: started
    enabled: true
  tags:
    - haproxy