---
- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present
  tags:
    - haproxy

# Included due to an issue with the existing haproxy template, app1/app2, work on prod not QA, vice-versa.
- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
  tags:
    - haproxy

- name: Ensure HAProxy Service is Enabled
  service:
    name: "{{ payload }}"
    state: started
    enabled: true
  tags:
    - haproxy