---
- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present
  tags:
    - haproxy

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
  tags:
    - haproxy
  ignore_errors: yes

- name: Print Config
  command: cat /etc/haproxy/haproxy.cfg
  register: test

- name: print test
  debug:
    msg: "{{ test.stdout }}"

- name: Ensure HAProxy Service is Enabled
  service:
    name: "{{ payload }}"
    state: started
    enabled: true
  tags:
    - haproxy