---
# why is this in here????
- name: start {{ payload }}
  service:
    name: tomcat
    state: started
  tags:
    - haproxy
  ignore_errors: yes

- name: restart_haproxy
  service:
    name: haproxy
    state: restarted
  tags:
    - haproxy
  ignore_errors: yes

